---
- name: Joindre un client Windows au domaine Samba AD
  hosts: windowsclient
  vars:
    domain_name: "example.local"
    domain_realm: "EXAMPLE.LOCAL"
    ad_dc_hostname: "dc1.example.local"
    domain_admin_user: "Administrator"
    domain_admin_password: "Esteban1#"

  tasks:
    - name: Définir le nom de l'ordinateur
      win_hostname:
        name: windows-client
      register: hostname_changed

    - name: Redémarrer si le nom d'hôte a changé
      win_reboot:
        msg: "Reboot après changement de nom d'hôte"
      when: hostname_changed.reboot_required

    - name: Joindre le domaine
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join

    - name: Redémarrer après jonction au domaine si nécessaire
      win_reboot:
        msg: "Reboot après jonction au domaine"
      when: domain_join.reboot_required
